application: midiwasynth
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /js
  static_dir: js

- url: /lib
  static_dir: lib

- url: /styles
  static_dir: styles

- url: /sounds
  static_dir: sounds
